// Рабочие картинки-заглушки
const IMG = (seed: number, w = 800, h = 600) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const HERMITAGE = {
  whatsapp: '79001234567',
  phone: '+7 (900) 123-45-67',
  email: 'info@hermitage-decor.ru',
  address: 'Москва, ул. Тверская, 12, салон HERMITAGE DECOR',

  categories: [
    { id: 'bedroom', name: 'Спальня', image: IMG(100, 800, 800) },
    { id: 'living', name: 'Гостиная', image: IMG(101, 800, 800) },
    { id: 'dining', name: 'Столовая', image: IMG(102, 800, 800) },
    { id: 'office', name: 'Кабинет', image: IMG(103, 800, 800) },
    { id: 'kitchen', name: 'Кухня', image: IMG(104, 800, 800) },
    { id: 'hallway', name: 'Прихожая', image: IMG(105, 800, 800) },
    { id: 'kids', name: 'Детская', image: IMG(106, 800, 800) },
    { id: 'soft', name: 'Мягкая мебель', image: IMG(107, 800, 800) },
    { id: 'dishes', name: 'Посуда', image: IMG(108, 800, 800) },
    { id: 'aromas', name: 'Ароматы', image: IMG(109, 800, 800) },
    { id: 'textile', name: 'Текстиль', image: IMG(110, 800, 800) },
  ],

  countries: [
    { id: 'italy', name: 'Италия', image: IMG(200, 600, 600) },
    { id: 'turkey', name: 'Турция', image: IMG(201, 600, 600) },
    { id: 'china', name: 'Китай', image: IMG(202, 600, 600) },
  ],

  brands: ['Poliform', 'Minotti', 'B&B Italia', 'Natuzzi', 'Roche Bobois', 'Flexform', 'Molteni&C', 'Cassina', 'Villeroy & Boch', 'Rosenthal', 'Diptyque', 'Jo Malone'],

  products: [
    {
      id: 'p1',
      name: 'Кровать Imperial Velvet',
      price: 289000,
      country: 'Италия',
      factory: 'Poliform',
      category: 'bedroom',
      color: 'Бежевый',
      material: 'Ткань, массив дуба',
      sizes: '200×220 см',
      sku: 'HD-BED-001',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: true,
      image: IMG(1, 800, 600),
      images: [IMG(1, 1200, 800), IMG(10, 1200, 800), IMG(11, 1200, 800)],
      description: 'Роскошная кровать с мягким изголовьем и благородной обивкой. Итальянское мастерство и безупречная эстетика для спальни премиум-класса.',
    },
    {
      id: 'p2',
      name: 'Диван Milano Lounge',
      price: 456000,
      country: 'Италия',
      factory: 'Minotti',
      category: 'living',
      color: 'Серый',
      material: 'Кожа, металл',
      sizes: '280×95×72 см',
      sku: 'HD-SOF-002',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: true,
      image: IMG(2, 800, 600),
      images: [IMG(2, 1200, 800), IMG(12, 1200, 800)],
      description: 'Элегантный модульный диван с глубокими сиденьями. Идеален для просторной гостиной в современном стиле.',
    },
    {
      id: 'p3',
      name: 'Обеденный стол Grand Oak',
      price: 198000,
      country: 'Турция',
      factory: 'Natuzzi',
      category: 'dining',
      color: 'Тёмный дуб',
      material: 'Массив дуба',
      sizes: '240×100×76 см',
      sku: 'HD-TBL-003',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: true,
      image: IMG(3, 800, 600),
      images: [IMG(3, 1200, 800)],
      description: 'Монументальный обеденный стол из массива дуба с натуральной текстурой дерева.',
    },
    {
      id: 'p4',
      name: 'Кресло Executive Leather',
      price: 124000,
      country: 'Италия',
      factory: 'B&B Italia',
      category: 'office',
      color: 'Коричневый',
      material: 'Натуральная кожа',
      sizes: '75×80×110 см',
      sku: 'HD-CHR-004',
      inStock: true,
      isNew: false,
      isSale: false,
      popular: true,
      image: IMG(4, 800, 600),
      images: [IMG(4, 1200, 800)],
      description: 'Классическое кресло руководителя с эргономичной поддержкой и премиальной отделкой.',
    },
    {
      id: 'p5',
      name: 'Кухонный гарнитур Aurora',
      price: 890000,
      country: 'Италия',
      factory: 'Molteni&C',
      category: 'kitchen',
      color: 'Белый матовый',
      material: 'МДФ, камень',
      sizes: 'по проекту',
      sku: 'HD-KIT-005',
      inStock: false,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(5, 800, 600),
      images: [IMG(5, 1200, 800)],
      description: 'Модульный кухонный гарнитур с фасадами без ручек и столешницей из натурального камня.',
    },
    {
      id: 'p6',
      name: 'Консоль Entry Classic',
      price: 87000,
      country: 'Китай',
      factory: 'Flexform',
      category: 'hallway',
      color: 'Чёрный',
      material: 'Мрамор, латунь',
      sizes: '140×40×85 см',
      sku: 'HD-CON-006',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: false,
      image: IMG(6, 800, 600),
      images: [IMG(6, 1200, 800)],
      description: 'Изысканная консоль для прихожей с мраморной столешницей и латунными деталями.',
    },
    {
      id: 'p7',
      name: 'Детская кровать Cloud',
      price: 156000,
      country: 'Турция',
      factory: 'Cassina',
      category: 'kids',
      color: 'Белый',
      material: 'Массив бука',
      sizes: '160×200 см',
      sku: 'HD-KID-007',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(7, 800, 600),
      images: [IMG(7, 1200, 800)],
      description: 'Нежная детская кровать с мягкими линиями и экологичными материалами.',
    },
    {
      id: 'p8',
      name: 'Пуф Royal Round',
      price: 45000,
      country: 'Китай',
      factory: 'Roche Bobois',
      category: 'soft',
      color: 'Золотистый',
      material: 'Бархат',
      sizes: 'Ø55×45 см',
      sku: 'HD-PUF-008',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: true,
      image: IMG(8, 800, 600),
      images: [IMG(8, 1200, 800)],
      description: 'Декоративный пуф с бархатной обивкой — акцент в любой комнате.',
    },
    {
      id: 'p9',
      name: 'Комод Heritage',
      price: 178000,
      country: 'Италия',
      factory: 'Poliform',
      category: 'bedroom',
      color: 'Орех',
      material: 'Шпон ореха',
      sizes: '160×50×80 см',
      sku: 'HD-COM-009',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(9, 800, 600),
      images: [IMG(9, 1200, 800)],
      description: 'Комод с шестью ящиками и фурнитурой премиум-класса.',
    },
    {
      id: 'p10',
      name: 'Журнальный столик Crystal',
      price: 92000,
      country: 'Италия',
      factory: 'Minotti',
      category: 'living',
      color: 'Прозрачный',
      material: 'Стекло, латунь',
      sizes: '90×90×40 см',
      sku: 'HD-TBL-010',
      inStock: true,
      isNew: false,
      isSale: false,
      popular: true,
      image: IMG(10, 800, 600),
      images: [IMG(10, 1200, 800)],
      description: 'Стеклянный столик с латунным основанием — лёгкость и роскошь.',
    },
    {
      id: 'p11',
      name: 'Стул Dining Velvet',
      price: 38000,
      country: 'Турция',
      factory: 'Natuzzi',
      category: 'dining',
      color: 'Изумрудный',
      material: 'Бархат, металл',
      sizes: '48×55×88 см',
      sku: 'HD-STL-011',
      inStock: true,
      isNew: true,
      isSale: true,
      popular: false,
      image: IMG(11, 800, 600),
      images: [IMG(11, 1200, 800)],
      description: 'Обеденный стул с мягким сиденьем и изящной спинкой.',
    },
    {
      id: 'p12',
      name: 'Стеллаж Library',
      price: 215000,
      country: 'Китай',
      factory: 'B&B Italia',
      category: 'office',
      color: 'Чёрный',
      material: 'Металл, стекло',
      sizes: '200×35×220 см',
      sku: 'HD-SHF-012',
      inStock: true,
      isNew: false,
      isSale: false,
      popular: false,
      image: IMG(12, 800, 600),
      images: [IMG(12, 1200, 800)],
      description: 'Открытый стеллаж для кабинета с подсветкой полок.',
    },

    // ===== ПОСУДА =====
    {
      id: 'p13',
      name: 'Ваза Ceramic Elegance',
      price: 12000,
      country: 'Италия',
      factory: 'B&B Italia',
      category: 'dishes',
      color: 'Белый',
      material: 'Керамика',
      sizes: '30×15 см',
      sku: 'HD-DIS-013',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(13, 800, 600),
      images: [IMG(13, 1200, 800)],
      description: 'Изысканная керамическая ваза ручной работы.',
    },
    {
      id: 'p14',
      name: 'Набор столовой посуды Classic',
      price: 45000,
      country: 'Италия',
      factory: 'Poliform',
      category: 'dishes',
      color: 'Белый',
      material: 'Фарфор',
      sizes: 'На 6 персон',
      sku: 'HD-DIS-014',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: true,
      image: IMG(14, 800, 600),
      images: [IMG(14, 1200, 800)],
      description: 'Элегантный набор столовой посуды из белого фарфора.',
    },
    {
      id: 'p15',
      name: 'Приборы Silver Line',
      price: 28000,
      country: 'Италия',
      factory: 'Minotti',
      category: 'dishes',
      color: 'Серебристый',
      material: 'Нержавеющая сталь',
      sizes: 'На 6 персон',
      sku: 'HD-DIS-015',
      inStock: true,
      isNew: false,
      isSale: false,
      popular: false,
      image: IMG(15, 800, 600),
      images: [IMG(15, 1200, 800)],
      description: 'Столовые приборы из нержавеющей стали с матовой отделкой.',
    },

    // ===== АРОМАТЫ =====
    {
      id: 'p16',
      name: 'Диффузор Home Essence',
      price: 8500,
      country: 'Италия',
      factory: 'Natuzzi',
      category: 'aromas',
      color: 'Прозрачный',
      material: 'Стекло, аромамасла',
      sizes: '200 мл',
      sku: 'HD-ARO-016',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: true,
      image: IMG(16, 800, 600),
      images: [IMG(16, 1200, 800)],
      description: 'Ароматический диффузор с натуральными маслами.',
    },
    {
      id: 'p17',
      name: 'Свеча Candle Luxe',
      price: 4500,
      country: 'Турция',
      factory: 'Cassina',
      category: 'aromas',
      color: 'Кремовый',
      material: 'Соевый воск',
      sizes: '300 г',
      sku: 'HD-ARO-017',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: false,
      image: IMG(17, 800, 600),
      images: [IMG(17, 1200, 800)],
      description: 'Ароматическая свеча из натурального соевого воска.',
    },
    {
      id: 'p18',
      name: 'Аромамасло Pure Essence',
      price: 3200,
      country: 'Китай',
      factory: 'Roche Bobois',
      category: 'aromas',
      color: 'Золотистый',
      material: 'Натуральные масла',
      sizes: '30 мл',
      sku: 'HD-ARO-018',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(18, 800, 600),
      images: [IMG(18, 1200, 800)],
      description: 'Натуральное эфирное масло для ароматерапии.',
    },

    // ===== ТЕКСТИЛЬ =====
    {
      id: 'p19',
      name: 'Постельное бельё Silk Dream',
      price: 35000,
      country: 'Италия',
      factory: 'Flexform',
      category: 'textile',
      color: 'Белый',
      material: 'Шёлк',
      sizes: '2-спальный',
      sku: 'HD-TEX-019',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: true,
      image: IMG(19, 800, 600),
      images: [IMG(19, 1200, 800)],
      description: 'Роскошное постельное бельё из натурального шёлка.',
    },
    {
      id: 'p20',
      name: 'Покрывало Velvet Touch',
      price: 22000,
      country: 'Турция',
      factory: 'B&B Italia',
      category: 'textile',
      color: 'Серый',
      material: 'Бархат',
      sizes: '240×260 см',
      sku: 'HD-TEX-020',
      inStock: true,
      isNew: false,
      isSale: true,
      popular: false,
      image: IMG(20, 800, 600),
      images: [IMG(20, 1200, 800)],
      description: 'Мягкое бархатное покрывало премиального качества.',
    },
    {
      id: 'p21',
      name: 'Плед Cashmere Soft',
      price: 18000,
      country: 'Италия',
      factory: 'Molteni&C',
      category: 'textile',
      color: 'Бежевый',
      material: 'Кашемир',
      sizes: '150×200 см',
      sku: 'HD-TEX-021',
      inStock: true,
      isNew: false,
      isSale: false,
      popular: true,
      image: IMG(21, 800, 600),
      images: [IMG(21, 1200, 800)],
      description: 'Тёплый плед из натурального кашемира.',
    },
    {
      id: 'p22',
      name: 'Подушка Comfort Plus',
      price: 8500,
      country: 'Китай',
      factory: 'Poliform',
      category: 'textile',
      color: 'Белый',
      material: 'Хлопок, пух',
      sizes: '50×70 см',
      sku: 'HD-TEX-022',
      inStock: true,
      isNew: true,
      isSale: false,
      popular: false,
      image: IMG(22, 800, 600),
      images: [IMG(22, 1200, 800)],
      description: 'Мягкая декоративная подушка с натуральным наполнителем.',
    },
  ],
};

export function formatPrice(n: number): string {
  return new Intl.NumberFormat('ru-RU').format(n) + ' ₽';
}

export interface Product {
  id: string;
  name: string;
  price: number;
  country: string;
  factory: string;
  category: string;
  color: string;
  material: string;
  sizes: string;
  sku: string;
  inStock: boolean;
  isNew: boolean;
  isSale: boolean;
  popular: boolean;
  image: string;
  images: string[];
  description: string;
}

export function getProduct(id: string): Product | undefined {
  return HERMITAGE.products.find((p) => p.id === id);
}